name: Flask Task Manager CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run tests (optional)
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest  # Replace this with your test command if necessary

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        run: |
          source venv/bin/activate
          az webapp up --name FlaskManager --resource-group FlaskManager_group --location "South India"
