name: Flask Task Manager CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest  # or any test command for your project

      - name: Deploy to Azure Web App
        run: |
          source venv/bin/activate
          az webapp up --name <your-app-name> --resource-group <your-resource-group> --location <your-location>
